name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_wGvDAonEOfE48cVrAcBG3Fxi
          vercel-project-id: prj_7jvO9OVEELRglsocaHEgplD3RlB7
          github-token: ${{ secrets.GITHUB_TOKEN }}
